package com.sb.elsinore.html;

import java.io.IOException;

import org.rendersnake.HtmlCanvas;
import org.rendersnake.Renderable;

import static org.rendersnake.HtmlAttributesFactory.*;

import com.sb.elsinore.BrewServer;
import com.sb.elsinore.LaunchControl;
import com.sb.elsinore.Messages;
import com.sb.elsinore.PID;

public class PIDComponent implements Renderable {

    private String name = null;
    private String type = null;

    public PIDComponent(String name) {
        this.name = name;
        if (LaunchControl.findPID(name) == null) {
            this.type = "temp";
        } else {
            this.type = "pid";
        }
    }

    @Override
    public void renderOn(HtmlCanvas html) throws IOException {
        if (this.name == null) {
            BrewServer.LOG.warning("NO Name set in PID Component!");
            return;
        }

        html.div(id(name)
                .class_("holo-content controller panel panel-primary " + type))
            .script()
                .write(TempComponent.getGaugeScript(name), false)
            ._script()
            .div(id(name + "-title").class_("title panel-heading")
                    .onClick("editDevice(this)"))
                .write(name)
            ._div()
            .div(id(name + "-error").class_("panel-error")
                    .onClick("dismissError(this)"))
            ._div()
            .div(id(name + "-body").class_("panel-body"))
                .canvas(id(name + "-tempGauge").class_("gauge")
                        .width(300).height(140))
                ._canvas()
                .div(id(name + "-tempSummary"))
                    .write(Messages.TEMPERATURE + "(")
                    .div(id("tempUnit")).write("F")._div()
                    .write("): ")
                    .div(id(name + "-tempStatus"))
                        .write("temp")
                    ._div().write("&#176", false)
                    .div(id("tempUnit")).write("F")._div()
                ._div();

            if (LaunchControl.recorderEnabled()) {
                html.div(id(name + "-graph_wrapper")
                        .class_("holo-content controller panel panel-info"))
                    .div(id(name + "-graph-title")
                            .class_("title panel-heading")
                            .onClick("embedGraph(\"" + name + "\");"
                                + " toggleBlock(\"" + name + "-graph_body\");")
                        )
                        .write(Messages.SHOW_GRAPH)
                    ._div()
                    .div(id(name + "-graph_body").onClick("showGraph(this);")
                            .class_("panel-body"))
                    ._div()
                ._div();
            }
            html.div()
                .div(id(name + "-controls").class_("controller"))
                    .div(id(name + "-gage").class_("gage"))._div()
                    .form(id(name + "-form").class_("controlPanelForm"))
                        .input(type("hidden").name("mode").id("mode"))
                        .input(type("hidden").name("deviceaddr").id("deviceaddr"))
                        .input(type("hidden").name("heatgpio").id("heatgpio"))
                        .input(type("hidden").name("coolgpio").id("coolgpio"))
                        .input(type("hidden").name("auxgpio").id("auxgpio"))
                        .input(type("hidden").name("cutoff").id("cutoff"))
                        .input(type("hidden").name("calibration").id("calibration"))
                        .input(type("hidden").name("hidden").id("hidden"))
                        .input(type("hidden").name("vol_ain").id("vol_ain"))
                        .input(type("hidden").name("vol_add").id("vol_add"))
                        .input(type("hidden").name("vol_off").id("vol_off"))
                        .input(type("hidden").name("vol_units").id("vol_units"))
                        .div(class_("holo-buttons").style("display: table"))
                            .div(style("display: table-row"))
                                .render(new ModeButton(name, "Auto", Messages.AUTO))
                                .render(new ModeButton(name, "Hysteria", Messages.HYSTERIA))
                            ._div()
                            .div(style("display: table-row"))
                                .render(new ModeButton(name, "Manual", Messages.MANUAL))
                                .render(new ModeButton(name, "Off", Messages.PID_OFF))
                            ._div()
                        ._div()
                        .table(id("pidInput").class_("labels table"))
                            .tr(id(name + "-SP").class_("holo-field"))
                                .td(id(name + "-labelSP"))
                                    .write(Messages.SET_POINT)
                                ._td()
                                .td(id(name + "-setpoint"))
                                    .input(class_("inputBox setpoint").type("text")
                                            .name("setpoint").maxlength("4")
                                            .size("4").value(""))
                                ._td()
                                .td(id(name + "-unitSP"))
                                    .div(id("tempUnit")).write("F")._div()
                                ._td()
                            ._tr()
                            .tr(id(name + "-DC").class_("holo-field"))
                                .td(id(name + "-labelDC"))
                                    .write(Messages.DUTY_CYCLE)
                                ._td()
                                .td(id(name + "-dutycycle"))
                                    .input(class_("inputBox dutycycle").type("text")
                                            .name("dutycycle").maxlength("6")
                                            .size("6").value(""))
                                ._td()
                                .td(id(name + "-unitDC"))
                                    .write("%")
                                ._td()
                            ._tr()
                            .tr(id(name + "-DT").class_("holo-field"))
                                .td(id(name + "-labelDT"))
                                    .write(Messages.DUTY_TIME)
                                ._td()
                                .td(id(name + "-cycletime"))
                                    .input(class_("inputBox dutytime").type("text")
                                            .name("cycletime").maxlength("6")
                                            .size("6").value(""))
                                ._td()
                                .td(id(name + "-unitDT"))
                                    .write(Messages.SECS)
                                ._td()
                            ._tr()
                            .write("<!-- Nav tabs -->", false)
                            .tr(id(name + "-tabbedInputs"))
                                .td(colspan("3"))
                                    .ul(id("inputtabs")
                                        .class_("nav nav-tabs")
                                        .role("tablist"))
                                        .li(class_("active"))
                                            .a(href("#heat").role("tab").add("data-toggle", "tab"))
                                                .content(Messages.HEAT)
                                        ._li()
                                        .li(class_("active"))
                                            .a(href("#cool").role("tab").add("data-toggle", "tab"))
                                                .content(Messages.COOL)
                                        ._li()
                                    ._ul()
                                    .div(class_("tab-content"))
                                        .div(class_("tab-pane active").id("heat"))
                                            .table()
                                                .tr(id(name + "-heatDT").class_("holo-field"))
                                                    .td(id(name + "-labelDT"))
                                                        .write(Messages.DUTY_TIME)
                                                    ._td()
                                                    .td(id(name + "-cycleTime"))
                                                        .input(class_("inputBox heatdutytime")
                                                            .name("heatcycletime")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitDT"))
                                                        .write(Messages.SECS)
                                                    ._td()
                                                ._tr()
                                                .tr(id(name + "-heatP").class_("holo-field"))
                                                    .td(id(name + "-labelp"))
                                                        .write("P")
                                                    ._td()
                                                    .td(id(name + "-pinput"))
                                                        .input(class_("inputBox heatp")
                                                            .name("heatp")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitP"))
                                                        .write(Messages.SECS + "/&#176", false)
                                                        .div(id("tempUnit"))
                                                            .write("F")
                                                        ._div()
                                                    ._td()
                                                ._tr()
                                                .tr(id(name + "-heatI").class_("holo-field"))
                                                    .td(id(name + "-labeli"))
                                                        .write("I")
                                                    ._td()
                                                    .td(id(name + "-iinput"))
                                                        .input(class_("inputBox heati")
                                                            .name("heati")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitI"))
                                                        .write(Messages.SECS + "&#176", false)
                                                        .div(id("tempUnit"))
                                                            .write("F")
                                                        ._div()
                                                    ._td()
                                                ._tr()
                                                .tr(id(name + "-heatD").class_("holo-field"))
                                                    .td(id(name + "-labeld"))
                                                        .write("I")
                                                    ._td()
                                                    .td(id(name + "-dinput"))
                                                        .input(class_("inputBox heatd")
                                                            .name("heatd")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitD"))
                                                        .write(Messages.SECS)
                                                    ._td()
                                                ._tr()
                                            ._table()
                                        ._div()
                                        .div(class_("tab-pane").id("cool"))
                                            .table()
                                                .tr(id(name + "-coolDT").class_("holo-field"))
                                                    .td(id(name + "-labelDT"))
                                                        .write(Messages.DUTY_TIME)
                                                    ._td()
                                                    .td(id(name + "-cycleTime"))
                                                        .input(class_("inputBox cooldutytime")
                                                            .name("coolcycletime")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitDT"))
                                                        .write(Messages.SECS)
                                                    ._td()
                                                ._tr()
                                                .tr(id(name + "-coolP").class_("holo-field"))
                                                    .td(id(name + "-labelp"))
                                                        .write("P")
                                                    ._td()
                                                    .td(id(name + "-pinput"))
                                                        .input(class_("inputBox coolp")
                                                            .name("coolp")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitP"))
                                                        .write(Messages.SECS + "/&#176", false)
                                                        .div(id("tempUnit"))
                                                            .write("F")
                                                        ._div()
                                                    ._td()
                                                ._tr()
                                                .tr(id(name + "-coolI").class_("holo-field"))
                                                    .td(id(name + "-labeli"))
                                                        .write("I")
                                                    ._td()
                                                    .td(id(name + "-iinput"))
                                                        .input(class_("inputBox cooli")
                                                            .name("cooli")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitI"))
                                                        .write(Messages.SECS + "&#176", false)
                                                        .div(id("tempUnit"))
                                                            .write("F")
                                                        ._div()
                                                    ._td()
                                                ._tr()
                                                .tr(id(name + "-coolD").class_("holo-field"))
                                                    .td(id(name + "-labeld"))
                                                        .write("I")
                                                    ._td()
                                                    .td(id(name + "-dinput"))
                                                        .input(class_("inputBox coold")
                                                            .name("coold")
                                                            .maxlength("6")
                                                            .size(6)
                                                            .value(""))
                                                    ._td()
                                                    .td(id(name + "-unitD"))
                                                        .write(Messages.SECS)
                                                    ._td()
                                                ._tr()
                                            ._table()
                                        ._div()
                                    ._div()
                                ._td()
                            ._tr()
                            .tr(id(name + "-min").class_("holo-field"))
                                .td(id(name + "-labelMin"))
                                    .write(Messages.MIN)
                                ._td()
                                .td(id(name + "-mininput"))
                                    .input(class_("inputbox min").name("min")
                                        .maxlength(6).size(6).value("6"))
                                ._td()
                                .td(id(name + "unitMin"))
                                    .write("&#176", false)
                                    .div(id("tempUnit")).write("F")._div()
                                ._td()
                            ._tr()
                            .tr(id(name + "-max").class_("holo-field"))
                                .td(id(name + "-labelMax"))
                                    .write(Messages.MAX)
                                ._td()
                                .td(id(name + "-maxinput"))
                                    .input(class_("inputbox miax").name("max")
                                        .maxlength(6).size(6).value(6))
                                ._td()
                                .td(id(name + "unitMax"))
                                    .write("&#176", false)
                                    .div(id("tempUnit")).write("F")._div()
                                ._td()
                            ._tr()
                            .tr(id(name + "-time").class_("holo-field"))
                                .td(id(name + "-labelTime"))
                                    .write(Messages.TIME)
                                ._td()
                                .td(id(name + "-timeinput"))
                                    .input(class_("inputbox time").name("time")
                                        .maxlength(6).size(6).value("6"))
                                ._td()
                                .td(id(name + "unitTime"))
                                    .write(Messages.MINUTES)
                                ._td()
                            ._tr()
                        ._table()
                        .div(class_("holo-buttons"))
                            .button(id(name + "Aux")
                                    .class_("holo-button pump")
                                    .onClick("toggleAux(\"" + name + "\"),"
                                        + " waitForMsg(); return false;'"))
                                .write(Messages.AUX_ON)
                            ._button()
                            .br()
                            .button(id("sendcommand").type("submit")
                                    .value("SubmitCommand")
                                    .onClick("submitForm(this.form); waitForMsg();"
                                        + " return false"))
                                .write(Messages.SEND_COMMAND)
                            ._button()
                        ._div()
                    ._form()
                ._div()
                .div(id(name + "-volume")
                        .onClick("editVolume(this);"))
                ._div()
            ._div()._div()
        ._div();
    }


}
