#!/bin/bash
sudo java -cp libs/framboos-0.0.1-SNAPSHOT.jar:libs/ini4j-0.5.2.jar:libs/json-20090211.jar:libs/httpclient-4.2.jar:libs/httpcore-4.2.jar:libs/commons-logging-1.1.1.jar:libs/joda-time-2.2.jar:libs/Cosm.jar:. CoreApplication

